name: Tests

on:
  pull_request:
    branches: [main, develop, feat/**]
    paths:
      - "**.py"
      - "tests/**"
      - "requirements.txt"
      - "requirements-dev.txt"
      - ".github/workflows/tests.yml"
  workflow_dispatch: {}

jobs:
  pytest:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            # fallback to ensure pytest exists if dev file isn't used
            pip install pytest
          fi

      - name: Run tests
        run: pytest -q
